//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriductsInOrders
    {
        public int id { get; set; }
        public int idOrder { get; set; }
        public int idProducts { get; set; }
        public int amountInOrder { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Products Products { get; set; }
    }
}
